### ISSUE TITLE
[Suggestion] add the demo url at the github repo link

### ISSUE THREAD

**Issue by erkobridee** [ektogamat/lensflare-threejs-vanilla#1]
Hi buddy, 

it would be nice to have the link for the demo that you had shared on twitter here on the repo too 😄 

https://lensflare-threejs-vanilla.vercel.app/

thanks o/

Best regards,
Erko Bridee

**Comment by ektogamat** [comment]
Ahhh yes! Very good point ehhe. I will add this now ;). Thank you.
